/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicPrivacyPolicyRouteImport } from './routes/_public/privacy-policy'
import { Route as PublicResourcesRouteImport } from './routes/_public/resources'
import { Route as PublicServicesRouteImport } from './routes/_public/services'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicBlogIndexRouteImport } from './routes/_public/blog.index'
import { Route as PublicBlogSlugRouteImport } from './routes/_public/blog.$slug'
import { Route as PublicBrandsIndexRouteImport } from './routes/_public/brands.index'
import { Route as PublicBrandsSlugRouteImport } from './routes/_public/brands.$slug'
import { Route as PublicCategoriesSlugRouteImport } from './routes/_public/categories.$slug'
import { Route as PublicProductsIndexRouteImport } from './routes/_public/products.index'
import { Route as PublicProductsSlugRouteImport } from './routes/_public/products.$slug'
import { Route as PublicSolutionsIndexRouteImport } from './routes/_public/solutions.index'
import { Route as PublicSolutionsSlugRouteImport } from './routes/_public/solutions.$slug'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPrivacyPolicyRoute = PublicPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicResourcesRoute = PublicResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicServicesRoute = PublicServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicBlogSlugRoute = PublicBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicBrandsIndexRoute = PublicBrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicBrandsSlugRoute = PublicBrandsSlugRouteImport.update({
  id: '/brands/$slug',
  path: '/brands/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicCategoriesSlugRoute = PublicCategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicProductsIndexRoute = PublicProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicProductsSlugRoute = PublicProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSolutionsIndexRoute = PublicSolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSolutionsSlugRoute = PublicSolutionsSlugRouteImport.update({
  id: '/solutions/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/resources': typeof PublicResourcesRoute
  '/services': typeof PublicServicesRoute
  '/terms': typeof PublicTermsRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/brands/$slug': typeof PublicBrandsSlugRoute
  '/categories/$slug': typeof PublicCategoriesSlugRoute
  '/products/$slug': typeof PublicProductsSlugRoute
  '/solutions/$slug': typeof PublicSolutionsSlugRoute
  '/blog/': typeof PublicBlogIndexRoute
  '/brands/': typeof PublicBrandsIndexRoute
  '/products/': typeof PublicProductsIndexRoute
  '/solutions/': typeof PublicSolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/resources': typeof PublicResourcesRoute
  '/services': typeof PublicServicesRoute
  '/terms': typeof PublicTermsRoute
  '/': typeof PublicIndexRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/brands/$slug': typeof PublicBrandsSlugRoute
  '/categories/$slug': typeof PublicCategoriesSlugRoute
  '/products/$slug': typeof PublicProductsSlugRoute
  '/solutions/$slug': typeof PublicSolutionsSlugRoute
  '/blog': typeof PublicBlogIndexRoute
  '/brands': typeof PublicBrandsIndexRoute
  '/products': typeof PublicProductsIndexRoute
  '/solutions': typeof PublicSolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/_public/resources': typeof PublicResourcesRoute
  '/_public/services': typeof PublicServicesRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/blog/$slug': typeof PublicBlogSlugRoute
  '/_public/brands/$slug': typeof PublicBrandsSlugRoute
  '/_public/categories/$slug': typeof PublicCategoriesSlugRoute
  '/_public/products/$slug': typeof PublicProductsSlugRoute
  '/_public/solutions/$slug': typeof PublicSolutionsSlugRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
  '/_public/brands/': typeof PublicBrandsIndexRoute
  '/_public/products/': typeof PublicProductsIndexRoute
  '/_public/solutions/': typeof PublicSolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy-policy'
    | '/resources'
    | '/services'
    | '/terms'
    | '/blog/$slug'
    | '/brands/$slug'
    | '/categories/$slug'
    | '/products/$slug'
    | '/solutions/$slug'
    | '/blog/'
    | '/brands/'
    | '/products/'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contact'
    | '/privacy-policy'
    | '/resources'
    | '/services'
    | '/terms'
    | '/'
    | '/blog/$slug'
    | '/brands/$slug'
    | '/categories/$slug'
    | '/products/$slug'
    | '/solutions/$slug'
    | '/blog'
    | '/brands'
    | '/products'
    | '/solutions'
  id:
    | '__root__'
    | '/_public'
    | '/_public/about'
    | '/_public/contact'
    | '/_public/privacy-policy'
    | '/_public/resources'
    | '/_public/services'
    | '/_public/terms'
    | '/_public/'
    | '/_public/blog/$slug'
    | '/_public/brands/$slug'
    | '/_public/categories/$slug'
    | '/_public/products/$slug'
    | '/_public/solutions/$slug'
    | '/_public/blog/'
    | '/_public/brands/'
    | '/_public/products/'
    | '/_public/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/privacy-policy': {
      id: '/_public/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PublicPrivacyPolicyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/resources': {
      id: '/_public/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof PublicResourcesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/services': {
      id: '/_public/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof PublicServicesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/blog/$slug': {
      id: '/_public/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof PublicBlogSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/brands/': {
      id: '/_public/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof PublicBrandsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/brands/$slug': {
      id: '/_public/brands/$slug'
      path: '/brands/$slug'
      fullPath: '/brands/$slug'
      preLoaderRoute: typeof PublicBrandsSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/categories/$slug': {
      id: '/_public/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof PublicCategoriesSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/products/': {
      id: '/_public/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof PublicProductsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/products/$slug': {
      id: '/_public/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof PublicProductsSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/solutions/': {
      id: '/_public/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof PublicSolutionsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/solutions/$slug': {
      id: '/_public/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof PublicSolutionsSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicPrivacyPolicyRoute: typeof PublicPrivacyPolicyRoute
  PublicResourcesRoute: typeof PublicResourcesRoute
  PublicServicesRoute: typeof PublicServicesRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBlogSlugRoute: typeof PublicBlogSlugRoute
  PublicBrandsSlugRoute: typeof PublicBrandsSlugRoute
  PublicCategoriesSlugRoute: typeof PublicCategoriesSlugRoute
  PublicProductsSlugRoute: typeof PublicProductsSlugRoute
  PublicSolutionsSlugRoute: typeof PublicSolutionsSlugRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
  PublicBrandsIndexRoute: typeof PublicBrandsIndexRoute
  PublicProductsIndexRoute: typeof PublicProductsIndexRoute
  PublicSolutionsIndexRoute: typeof PublicSolutionsIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicPrivacyPolicyRoute: PublicPrivacyPolicyRoute,
  PublicResourcesRoute: PublicResourcesRoute,
  PublicServicesRoute: PublicServicesRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicBlogSlugRoute: PublicBlogSlugRoute,
  PublicBrandsSlugRoute: PublicBrandsSlugRoute,
  PublicCategoriesSlugRoute: PublicCategoriesSlugRoute,
  PublicProductsSlugRoute: PublicProductsSlugRoute,
  PublicSolutionsSlugRoute: PublicSolutionsSlugRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
  PublicBrandsIndexRoute: PublicBrandsIndexRoute,
  PublicProductsIndexRoute: PublicProductsIndexRoute,
  PublicSolutionsIndexRoute: PublicSolutionsIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
